### ISSUE TITLE
Redis is now ®, not ™

### ISSUE THREAD

**Issue by laysauchoa** [aiven/aiven-examples#55]
Mainly based on @TibsAtWork at https://github.com/aiven/devportal/issues/938

Steps:
1. Replace all of the occurrences of Redis™* with Redis®*
2. Update the footer text acknowledging registration marks to say that *Redis is a registered trademark of Redis Ltd. and the Redis box logo is a mark of Redis Ltd. Any rights therein are reserved to Redis Ltd. 

Source: https://redis.io/docs/about/trademark/

**Comment by dragonlancewu** [comment]
Hi @TibsAtWork and @laysauchoa here's my PR: https://github.com/aiven/aiven-examples/pull/58
